name: system_resources_2
description: Provides easy access to system resources (CPU load, memory usage).
version: 1.6.0
repository: https://github.com/jonasroussel/system_resources
homepage: https://github.com/jonasroussel/system_resources#readme

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
