name: system_resources_2
description: Provides easy access to system resources (CPU load, memory usage).
version: 2.0.0
repository: https://github.com/serverpod/system_resources_2
homepage: https://github.com/serverpod/system_resources_2#readme

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  hooks: ^1.0.0
  code_assets: ^1.0.0
  native_toolchain_c: ^0.17.0
  logging: ^1.2.0
  test: ^1.25.0
  lints: ^5.0.0
